### ISSUE TITLE
Investigate and fix the failing `PR Checks`

### ISSUE THREAD

**Issue by deyanzz** [hashgraph/hedera-sdk-cpp#368] opened 2023-06-13 11:38 UTC
### Description

All recent attempts to run the `PR Checks` Action during a new PR are always failing.
Sample error message:

>  [213/240] Linking CXX executable sdk/examples/Debug/hedera-sdk-cpp-create-stateful-contract-example
  FAILED: sdk/examples/Debug/hedera-sdk-cpp-create-stateful-contract-example 

Samples for failed `PR Checks`:
 - [Integration tests - common logic to setup the local node - Part 2 (PR)](https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/5246174041)
 - [Add `CustomFeeBase` base class ](https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/5246371878)
 - [Implement `CustomFixedFee`](https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/5247075909)
 - [Add `FeeAssessmentMethod`](https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/5247378637)

### Steps to reproduce

1. Create a new branch starting from `main` branch
2. Make a change in any file. It's enough to add a comment only.
3. Commit the change and `push` it to `origin`.
4. Open a new PR with the changes from the newly created branch.
5. Check the `PR Checks` action flow.

### Hedera network

other

### Version

0.9.0

### Operating system

None

**Comment by deyanzz** [comment] 2023-06-13 11:41
Tested with a new branch `main-from-2023-06-09__16_30`, which starts from main branch version of `09.06.2023 16:30` - [PR Checks Action](https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/5254743059/jobs/9493734788)

**Comment by deyanzz** [comment] 2023-06-13 11:46
Trying with a new branch `main-from-2023-06-07__16_40`, which starts from `main` branch version of `07.06.2023 16:40` - [PR Checks Action](https://github.com/hashgraph/hedera-sdk-cpp/pull/369).

**Comment by isavov** [comment] 2023-06-14 08:42
I've investigated the issue and it seems the linker is unable to link the executables with the current release of protobufs 
https://github.com/hashgraph/hedera-protobufs-cpp/releases/tag/v0.36.0
Building the hedera-protobufs-cpp repo from source and using that version of `libhapi.a` resolves it for me on Linux. I don't know what changed since the artifacts for the protobufs repo were built, but it seems it causes this incompatibility.

**Comment by rwalworth** [comment] 2023-06-14 14:13
> I've investigated the issue and it seems the linker is unable to link the executables with the current release of protobufs https://github.com/hashgraph/hedera-protobufs-cpp/releases/tag/v0.36.0 Building the hedera-protobufs-cpp repo from source and using that version of `libhapi.a` resolves it for me on Linux. I don't know what changed since the artifacts for the protobufs repo were built, but it seems it causes this incompatibility.

Would you suggest we regenerate the artifacts for the `v0.36` release then? Seems very strange that this problem came up out of nowhere

**Comment by isavov** [comment] 2023-06-14 14:22
> > I've investigated the issue and it seems the linker is unable to link the executables with the current release of protobufs https://github.com/hashgraph/hedera-protobufs-cpp/releases/tag/v0.36.0 Building the hedera-protobufs-cpp repo from source and using that version of `libhapi.a` resolves it for me on Linux. I don't know what changed since the artifacts for the protobufs repo were built, but it seems it causes this incompatibility.
> 
> Would you suggest we regenerate the artifacts for the `v0.36` release then? Seems very strange that this problem came up out of nowhere

I think that might solve the issue. I'm not that familiar with all the details of the configuration of this project - i.e. if all dependencies are pinned etc, as well as if there's been any changes to the runner's configs recently, so I can't really pinpoint the root cause of the issue, but I think regenerating the artifacts would resolve it.

**Comment by rwalworth** [comment] 2023-06-14 14:25
> > > I've investigated the issue and it seems the linker is unable to link the executables with the current release of protobufs https://github.com/hashgraph/hedera-protobufs-cpp/releases/tag/v0.36.0 Building the hedera-protobufs-cpp repo from source and using that version of `libhapi.a` resolves it for me on Linux. I don't know what changed since the artifacts for the protobufs repo were built, but it seems it causes this incompatibility.
> > 
> > 
> > Would you suggest we regenerate the artifacts for the `v0.36` release then? Seems very strange that this problem came up out of nowhere
> 
> I think that might solve the issue. I'm not that familiar with all the details of the configuration of this project - i.e. if all dependencies are pinned etc, as well as if there's been any changes to the runner's configs recently, so I can't really pinpoint the root cause of the issue, but I think regenerating the artifacts would resolve it.

Great! I'll give that a try and leave a comment here to see if it resolves the issue or not

**Comment by rwalworth** [comment] 2023-06-14 14:35
It actually might be a good idea to just upgrade to the `v0.37` build of protobufs and see if that fixes this issue as well.

**Comment by rwalworth** [comment] 2023-06-14 17:41
The builds are working now, I'm going to close this issue.

**Closed by rwalworth** 2023-06-14 17:41 UTC
Labels: Bug
