### ISSUE TITLE
TCK-CPP: Implement `AccountDeleteTransaction` JSON-RPC Endpoint

### ISSUE THREAD

**Issue by gsstoykov** [hashgraph/hedera-sdk-cpp#668] opened 2024-02-28 11:36 UTC
### Problem

`AccountDeleteTransaction` test isn't covered by the TCK-CPP server.

### Solution

We should implement JSON-RPC methods (endpoints) for `AccountDeleteTransaction` for the TCK-CPP server.

**Comment by rwalworth** [comment] 2024-09-18 17:43
Duplicate of #739. Closing

**Closed by rwalworth** 2024-09-18 17:43 UTC
Labels: Duplicate, New Feature
