### ISSUE TITLE
`TCK-CPP`: Implement `AccountUpdateTransaction` JSON-RPC Endpoint

### ISSUE THREAD

**Issue by gsstoykov** [hashgraph/hedera-sdk-cpp#670] opened 2024-02-28 11:40 UTC
### Problem

`AccountUpdateTransaction`  test isn't covered by the TCK-CPP server.

### Solution

We should implement JSON-RPC methods (endpoints) for `AccountUpdateTransaction`  for the TCK-CPP server.

**Comment by rwalworth** [comment] 2024-09-18 17:39
Duplicate of #702. Closing

**Closed by rwalworth** 2024-09-18 17:39 UTC
Labels: Duplicate, New Feature
